package br.inf.portalfiscal.wsdl.nfeinutilizacao2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 *
 */
@WebService(name = "NfeInutilizacao2Soap12", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class,
    br.inf.portalfiscal.nfe.nfeinutilizacao.ObjectFactory.class
})
public interface NfeInutilizacao2Soap12 {

    /**
     * Inutilizacao de numeracao de NF-e
     *
     * @param nfeDadosMsg
     * @param nfeCabecMsg
     * @return returns
     * br.inf.portalfiscal.nfe.wsdl.nfeinutilizacao2.NfeInutilizacaoNF2Result
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2/nfeInutilizacaoNF2")
    @WebResult(name = "nfeInutilizacaoNF2Result", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2", partName = "nfeInutilizacaoNF2Result")
    public NfeInutilizacaoNF2Result nfeInutilizacaoNF2(
            @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2", partName = "nfeDadosMsg") NfeDadosMsg nfeDadosMsg,
            @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2", partName = "nfeCabecMsg", header = true) Holder<NfeCabecMsg> nfeCabecMsg);

}
