package br.inf.portalfiscal.wsdl.consultacadastro;

import br.inf.portalfiscal.wsdl.consultacadastro.ConsultaCadastro2Result;
import br.inf.portalfiscal.wsdl.consultacadastro.NfeDadosMsg;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 *
 */
@WebService(name = "CadConsultaCadastro2Soap12", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class,
    br.inf.portalfiscal.nfe.consultacadastro.ObjectFactory.class    
})
public interface CadConsultaCadastro2Soap12 {

    /**
     *
     * @param nfeDadosMsg
     * @param nfeCabecMsg
     * @return returns
     * br.inf.portalfiscal.nfe.wsdl.cadconsultacadastro2.ConsultaCadastro2Result
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2/consultaCadastro2")
    @WebResult(name = "consultaCadastro2Result", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", partName = "consultaCadastro2Result")
    public ConsultaCadastro2Result consultaCadastro2(
            @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", partName = "nfeDadosMsg") NfeDadosMsg nfeDadosMsg,
            @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", partName = "nfeCabecMsg", header = true) Holder<NfeCabecMsg> nfeCabecMsg);

}
